create table "public"."twist" (
    "id" bigint generated by default as identity not null,
    "text" character varying not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" bigint not null
);


alter table "public"."twist" enable row level security;

create table "public"."user" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "handle" character varying not null,
    "name" character varying not null,
    "bio" character varying
);


alter table "public"."user" enable row level security;

CREATE UNIQUE INDEX twist_pkey ON public.twist USING btree (id);

CREATE UNIQUE INDEX user_handle_key ON public."user" USING btree (handle);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

alter table "public"."twist" add constraint "twist_pkey" PRIMARY KEY using index "twist_pkey";

alter table "public"."user" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."twist" add constraint "twist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) not valid;

alter table "public"."twist" validate constraint "twist_user_id_fkey";

alter table "public"."user" add constraint "user_handle_key" UNIQUE using index "user_handle_key";



